Repository CA-G12/Project-W5-Haleem-Nader, pull requests merged in 2022-08, with the labels that each got.

#4 installed express
  package-lock.json
  package.json
Labels: reviewed

#6 Create the server localhost at port 4001 in the server.js file
  src/server.js
Labels: awaiting review

#10 Create Pages for Errors
  public/css/404page.css
  public/css/500page.css
  public/index.html
  public/pages/404page.html
  public/pages/500page.html
  public/pages/landing.html
Labels: reviewed

#16 handle codes but we need to move it to routes.js
  public/index.html
  src/routes/routes.js
  src/server.js
Labels: reviewed

#17 created landing page and styled it and added assets file to hold imag…
  public/assets/img/author_pic.png
  public/assets/img/lower_quote.png
  public/assets/img/upper_quote.png
  public/css/landing.css
  public/pages/landing.html
Labels: done

#19 Edit file structure
  src/controllers/error.js
  src/controllers/index.js
  src/routes.js
Labels: reviewed

#21 created dom file and edited file structure to avoid deployment issues
  public/js/dom.js
  public/landing.html
Labels: done

#23 22 delete files
  public/index.html
  public/pages/landing.html
Labels: done

#24 created README file relates #13
  README.md
Labels: done

#26 Edit all Server codes
  public/index.html
  src/routes.js
  src/server.js
Labels: reviewed

#28 created logic.js functions
  public/js/logic.js
Labels: done

#31 Create router.js file
  src/router.js
  src/server.js
Labels: reviewed

#33 Edit-Server-Port
  src/server.js
Labels: reviewed

#34 Update README.md
  README.md
Labels: done

#36 upDate-logic.js
  public/index.html
  public/js/dom.js
  public/js/logic.js
Labels: reviewed

#37 fetch random quotes and authors
  public/js/logic.js
  public/js/test.js
  src/server.js
Labels: awaiting review

#38 added fetch quotes by author name
  public/js/logic.js
  src/router.js
  src/routes.js
  src/server.js
Labels: awaiting review

#41 Fix all bugs we have
  public/css/landing.css
  public/css/style.css
  public/index.html
  public/js/dom.js
  public/js/logic.js
  src/controllers/error.js
  src/controllers/index.js
  src/server.js
  src/test.js
Labels: reviewed

#43 fix the lower case and upper case
  public/index.html
  src/server.js
Labels: reviewed

#45 list header
  public/css/landing.css
  public/index.html
Labels: reviewed
